name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff mypy pytest
    - name: Lint
      run: |
        ruff check .
    - name: Type check
      run: |
        mypy src || true
    - name: Tests
      run: |
        pytest -q || true